# UVNet Universal Decompiler (uvudec)
# Copyright 2008 John McMaster <JohnDMcMaster@gmail.com>
# Licensed under terms of the three clause BSD license, see LICENSE for details

EXE_NAME=$(UVUDEC_EXE)

CC_SRCS =   \

CXX_SRCS = 	\
			$(UVUDEC_DIR)/main.cpp \

# Why is this needed?
USING_LIB_UVUDEC=Y

ROOT_DIR=..
include $(ROOT_DIR)/Makefile.mk
