# UVNet Universal Decompiler (uvudec)
# Copyright 2008 John McMaster <JohnDMcMaster@gmail.com>
# Licensed under terms of the three clause BSD license, see LICENSE for details

ifeq ($(EXE_BUILD_SUFFIX),Y)
ifeq ($(LINKAGE),static)
EXE_NAME_FULL=$(EXE_NAME).static
else
EXE_NAME_FULL=$(EXE_NAME).dynamic
endif
else
EXE_NAME_FULL=$(EXE_NAME)
endif

$(EXE_NAME_FULL): depend $(OBJS)
	mkdir -p $(BIN_DIR)
	$(CC) $(LDFLAGS) $(OBJS) $(LIBS) $(LIBS) -o $(EXE_NAME_FULL)
ifeq ($(USING_UPX),Y)
	$(UPX) $(UVUDEC_EXE)
endif

ALL_TARGETS=$(EXE_NAME_FULL)

ifeq ($(LINKAGE),static)

LIB_C_STATIC=$(shell $(CXX) -print-file-name=libc.a)
LIB_STDCXX_STATIC=$(shell $(CXX) -print-file-name=libstdc++.a)
LIB_M_STATIC=$(shell $(CXX) -print-file-name=libm.a)
LIBS += $(LIB_M_STATIC) $(LIB_STDCXX_STATIC) $(LIB_C_STATIC)

LDFLAGS += -static -static-libgcc -Wl,'-z nodefaultlib'

else

LIBS +=
LDFLAGS +=

endif

# Need to make macro for this
ifeq ($(USING_LIB_UVUDEC),Y)
ifeq ($(LINKAGE),static)
LIBS += $(LIB_UVUDEC_STATIC)
else
LIBS += -l$(LIB_UVUDEC_DYNAMIC_USED)
endif
endif

INFO_TARGETS=infoExe
infoExe:
	@(echo "Exe info")
	@(echo "EXE_NAME_FULL: $(EXE_NAME_FULL)")
	@(echo "")

