# UVD assembly engine plugin
# UVNet Universal Decompiler (uvudec)
# Copyright 2010 John McMaster <JohnDMcMaster@gmail.com>
# Licensed under the terms of the LGPL V3 or later, see COPYING for details

ROOT_DIR=../..
PLUGIN_NAME=uvdbfd

CC_SRCS =   \

CXX_SRCS = 	\
			flirt/flirt.cpp \
			flirt/core.cpp \
			flirt/function.cpp \
			flirt/module.cpp \
			flirt/module_printer.cpp \
			flirt/relocation.cpp \
			flirt/section.cpp \
			architecture.cpp \
			instruction.cpp \
			main.cpp \
			object.cpp \
			plugin.cpp \

include ../Makefile.mk

