# strings plugin
# UVNet Universal Decompiler (uvudec)
# Copyright 2010 John McMaster <JohnDMcMaster@gmail.com>
# Licensed under terms of the three clause BSD license, see LICENSE for details

ROOT_DIR=../..
PLUGIN_NAME=uvstrings

CC_SRCS =   \

CXX_SRCS = 	\
			main.cpp

include ../Makefile.mk

