# UVNet Universal Decompiler (uvudec)
# Copyright 2008 John McMaster <JohnDMcMaster@gmail.com>
# Licensed under terms of the three clause BSD license, see LICENSE for details

EXE_NAME=$(OMF2PAT_EXE)

OMF2PAT_DIR=$(ROOT_DIR)/omf2pat

CC_SRCS =   \

CXX_SRCS = 	\
			$(OMF2PAT_DIR)/main.cpp \

USING_LIB_UVUDEC=Y

ROOT_DIR=..
include $(ROOT_DIR)/Makefile.mk
