# UVD assembly engine plugin
# UVNet Universal Decompiler (uvudec)
# Copyright 2010 John McMaster <JohnDMcMaster@gmail.com>
# Licensed under the terms of the LGPL V3 or later, see COPYING for details

ROOT_DIR=../..
PLUGIN_NAME=uvdasm

CC_SRCS =   \

CXX_SRCS = 	\
			architecture.cpp \
			architecture_init.cpp \
			config.cpp \
			config_symbol.cpp \
			function.cpp \
			instruction.cpp \
			interpreter.cpp \
			main.cpp \
			operand.cpp \
			opcode_table.cpp \
			plugin.cpp \
			util.cpp \
			interpreter/interpreter.cpp \
			interpreter/javascript.cpp \
			interpreter/javascript_spiderape.cpp \
			interpreter/javascript_spidermonkey.cpp \
			interpreter/lua.cpp \
			interpreter/operator.cpp \
			interpreter/python.cpp \
			interpreter/python_api.cpp \
			interpreter/python_exec.cpp \

include ../Makefile.mk

