# UVNet Universal Decompiler (uvudec)
# Copyright 2008 John McMaster <JohnDMcMaster@gmail.com>
# Licensed under terms of the three clause BSD license, see LICENSE for details

EXE_NAME=$(OBJ2PAT_EXE)

OBJ2PAT_DIR=$(ROOT_DIR)/obj2pat

CC_SRCS =   \

CXX_SRCS = 	\
			$(OBJ2PAT_DIR)/main.cpp \

LIBS += -luvdflirt
USING_LIB_UVUDEC=Y

ROOT_DIR=..
include $(ROOT_DIR)/Makefile.mk
