configure:
	cd uvudec/uvudec && autoconf
	cd uvudec/uvudec && ./configure
	
all:
	cd uvudec/uvudec && $(MAKE) all

test:
	cd uvudec/uvudec && $(MAKE) test

run_test:
	cd uvudec/uvudec && $(MAKE) run_test

