# UVD assembly engine plugin
# UVNet Universal Decompiler (uvudec)
# Copyright 2010 John McMaster <JohnDMcMaster@gmail.com>
# Licensed under the terms of the LGPL V3 or later, see COPYING for details

ROOT_DIR=../..

CC_SRCS =   \

CXX_SRCS = 	\
			main.cpp \
			object.cpp \
			plugin.cpp \

include ../Makefile.mk

