# UVNet Universal Decompiler (uvudec)
# Copyright 2008 John McMaster <JohnDMcMaster@gmail.com>
# Licensed under terms of the three clause BSD license, see LICENSE for details

EXE_NAME=$(COFF2PAT_EXE)

COFF2PAT_DIR=$(ROOT_DIR)/coff2pat

CC_SRCS =   \

CXX_SRCS = 	\
			$(COFF2PAT_DIR)/main.cpp \

USING_LIB_UVUDEC=Y

ROOT_DIR=..
include $(ROOT_DIR)/Makefile.mk
