#!/usr/bin/python

import os

os.system("find ../libuvudec/ -mindepth 3 -name '*.h' -exec fgrep '**' {} ';' |sed 's/^.*[(]//g' |sed 's/[)].*$//g' |awk -F ',' '{ for(i=1;i<=NF;++i) print $i  }' |fgrep '**' |fgrep -v '***' |tr -d '[:blank:]' |grep -v '^$' |fgrep UVD |awk -F '**' '{ print $1 }' |sort -u >temp_types.txt")
out = open('gen_typemaps.i', 'w')
out.write('//WARNING: this file is automatically generated, do not edit it\n')
for line in open('temp_types.txt').readlines():
	uvd_type = line.strip()
	out.write("""
//%s
%%typemap(in, numinputs=0) %s ** (%s *temp)
{
	$1 = &temp;
}

%%typemap(argout) (%s **)
{
	PyObject *to_add = SWIG_NewPointerObj(*$1, $descriptor(%s *), SWIG_POINTER_OWN);
	$result = SWIG_AppendOutput($result, to_add);
}

""" % (uvd_type, uvd_type, uvd_type, uvd_type, uvd_type))

out.close()
os.system('rm -f temp_types.txt')

