# UVNet Universal Decompiler (uvudec)
# Copyright 2008 John McMaster <JohnDMcMaster@gmail.com>
# Licensed under terms of the three clause BSD license, see LICENSE for details

FLIRTUTIL_DIR=$(ROOT_DIR)/flirtutil
FLIRTUTIL_EXE=$(BIN_DIR)/uvflirtutil
EXE_NAME=$(FLIRTUTIL_EXE)

CC_SRCS =   \

CXX_SRCS = 	\
			$(FLIRTUTIL_DIR)/main.cpp \

USING_LIB_UVUDEC=Y

ROOT_DIR=..
include $(ROOT_DIR)/Makefile.mk
