# UVNet Universal Decompiler (uvudec)
# Copyright 2008 John McMaster <JohnDMcMaster@gmail.com>
# Licensed under terms of the three clause BSD license, see LICENSE for details

EXE_NAME=$(PAT2SIG_EXE)

PAT2SIG_DIR=$(ROOT_DIR)/pat2sig

CC_SRCS =   \

CXX_SRCS = 	\
			$(PAT2SIG_DIR)/main.cpp \

USING_LIB_UVUDEC=Y

ROOT_DIR=..
include $(ROOT_DIR)/Makefile.mk
