# UVNet Universal Decompiler (uvudec)
# Copyright 2008 John McMaster <JohnDMcMaster@gmail.com>
# Licensed under the terms of the LGPL V3 or later, see COPYING for details

EXE_NAME=$(PAT2SIG_EXE)

PAT2SIG_DIR=$(ROOT_DIR)/pat2sig

CC_SRCS =   \

CXX_SRCS = 	\
			$(PAT2SIG_DIR)/main.cpp \

LIBS += -luvdflirt
USING_LIB_UVUDEC=Y

ROOT_DIR=..
include $(ROOT_DIR)/Makefile.mk
