# UVNet Universal Decompiler (uvudec)
# Copyright 2008 John McMaster <JohnDMcMaster@gmail.com>
# Licensed under terms of the three clause BSD license, see LICENSE for details

EXE_NAME=$(BIN2OBJ_EXE)

CC_SRCS =   \

CXX_SRCS = 	\
			main.cpp \

USING_LIB_UVUDEC=Y

LIBS += -luvdelf

ROOT_DIR=..
include $(ROOT_DIR)/Makefile.mk

