# UVNet Universal Decompiler (uvudec)
# Copyright 2008 John McMaster <JohnDMcMaster@gmail.com>
# Licensed under terms of the three clause BSD license, see LICENSE for details

EXE_NAME=$(BIN2OBJ_EXE)

BIN2OBJ_DIR=$(ROOT_DIR)/bin2obj

CC_SRCS =   \

CXX_SRCS = 	\
			$(BIN2OBJ_DIR)/main.cpp \

USING_LIB_UVUDEC=Y

ROOT_DIR=..
include $(ROOT_DIR)/Makefile.mk

