# UVNet Universal Decompiler (uvudec)
# Copyright 2008 John McMaster <JohnDMcMaster@gmail.com>
# Licensed under terms of the three clause BSD license, see LICENSE for details

LIB_NAME=$(LIB_UVUDEC)

CC_SRCS =   \

CXX_SRCS = 	\
			$(ASSEMBLY_DIR)/uvd_address.cpp \
			$(ASSEMBLY_DIR)/uvd_binary_function.cpp \
			$(ASSEMBLY_DIR)/uvd_binary_symbol.cpp \
			$(ASSEMBLY_DIR)/uvd_cpu.cpp \
			$(ASSEMBLY_DIR)/uvd_cpu_vector.cpp \
			$(ASSEMBLY_DIR)/uvd_instruction.cpp \
			$(ASSEMBLY_DIR)/uvd_opcode.cpp \
			$(ASSEMBLY_DIR)/uvd_operand.cpp \
			$(ASSEMBLY_DIR)/uvd_register.cpp \
			$(COMPILER_DIR)/uvd_compiler.cpp \
			$(COMPILER_DIR)/uvd_compiler_assembly.cpp \
			$(COMPILER_DIR)/uvd_compiler_gcc.cpp \
			$(CORE_DIR)/uvd.cpp \
			$(CORE_DIR)/uvd_analysis.cpp \
			$(CORE_DIR)/uvd_analysis_db.cpp \
			$(CORE_DIR)/uvd_analyzer.cpp \
			$(CORE_DIR)/uvd_core_event.cpp \
			$(CORE_DIR)/uvd_iterator.cpp \
			$(DATA_DIR)/uvd_data.cpp \
			$(DATA_DIR)/uvd_data_chunk.cpp \
			$(DATA_DIR)/uvd_data_file.cpp \
			$(DATA_DIR)/uvd_data_memory.cpp \
			$(DATA_DIR)/uvd_data_placeholder.cpp \
			$(EVENT_DIR)/engine.cpp \
			$(EVENT_DIR)/event.cpp \
			$(ELF_DIR)/uvd_elf.cpp \
			$(ELF_DIR)/uvd_elf_data.cpp \
			$(ELF_DIR)/uvd_elf_header.cpp \
			$(ELF_DIR)/uvd_elf_init.cpp \
			$(ELF_DIR)/uvd_elf_relocation.cpp \
			$(ELF_DIR)/uvd_elf_string_table.cpp \
			$(ELF_DIR)/uvd_elf_symbol.cpp \
			$(ELF_DIR)/uvd_elf_writer.cpp \
			$(FLIRT_DIR)/pat/bfd/bfd.cpp \
			$(FLIRT_DIR)/pat/bfd/core.cpp \
			$(FLIRT_DIR)/pat/bfd/function.cpp \
			$(FLIRT_DIR)/pat/bfd/function_printer.cpp \
			$(FLIRT_DIR)/pat/bfd/relocation.cpp \
			$(FLIRT_DIR)/pat/bfd/section.cpp \
			$(FLIRT_DIR)/config.cpp \
			$(FLIRT_DIR)/lib/bfd.cpp \
			$(FLIRT_DIR)/lib/elf.cpp \
			$(FLIRT_DIR)/lib/lib.cpp \
			$(FLIRT_DIR)/args.cpp \
			$(FLIRT_DIR)/flirt.cpp \
			$(FLIRT_DIR)/function.cpp \
			$(FLIRT_DIR)/pat/pat.cpp \
			$(FLIRT_DIR)/pat/uvd.cpp \
			$(FLIRT_DIR)/sig/tree/basic_node.cpp \
			$(FLIRT_DIR)/sig/tree/hash_node.cpp \
			$(FLIRT_DIR)/sig/tree/leading_node.cpp \
			$(FLIRT_DIR)/sig/format.cpp \
			$(FLIRT_DIR)/sig/sig.cpp \
			$(FLIRT_DIR)/sig/writer.cpp \
			$(HASH_DIR)/uvd_crc.cpp \
			$(HASH_DIR)/uvd_md5.cpp \
			$(HASH_DIR)/uvd_md5_GNU.cpp \
			$(INIT_DIR)/uvd_arg.cpp \
			$(INIT_DIR)/uvd_arg_util.cpp \
			$(INIT_DIR)/uvd_config.cpp \
			$(INIT_DIR)/uvd_config_interpreter.cpp \
			$(INIT_DIR)/uvd_config_symbol.cpp \
			$(INIT_DIR)/uvd_config_symbols.cpp \
			$(INIT_DIR)/uvd_init.cpp \
			$(INTERPRETER_DIR)/uvd_interpreter.cpp \
			$(INTERPRETER_DIR)/uvd_javascript.cpp \
			$(INTERPRETER_DIR)/uvd_javascript_spiderape.cpp \
			$(INTERPRETER_DIR)/uvd_javascript_spidermonkey.cpp \
			$(INTERPRETER_DIR)/uvd_lua.cpp \
			$(INTERPRETER_DIR)/uvd_operator.cpp \
			$(INTERPRETER_DIR)/uvd_python.cpp \
			$(INTERPRETER_DIR)/uvd_python_api.cpp \
			$(INTERPRETER_DIR)/uvd_python_exec.cpp \
			$(LANGUAGE_DIR)/uvd_format.cpp \
			$(LANGUAGE_DIR)/uvd_language.cpp \
			$(PLUGIN_DIR)/plugin.cpp \
			$(RELOCATION_DIR)/uvd_relocatable_data.cpp \
			$(RELOCATION_DIR)/uvd_relocatable_element.cpp \
			$(RELOCATION_DIR)/uvd_relocation.cpp \
			$(RELOCATION_DIR)/uvd_relocation_fixup.cpp \
			$(RELOCATION_DIR)/uvd_relocation_manager.cpp \
			$(RELOCATION_DIR)/uvd_relocation_writer.cpp \
			$(RELOCATION_DIR)/uvd_simple_relocation_fixup.cpp \
			$(UTIL_DIR)/io.cpp \
			$(UTIL_DIR)/uvd_ascii_art.cpp \
			$(UTIL_DIR)/uvd_benchmark.cpp \
			$(UTIL_DIR)/uvd_debug.cpp \
			$(UTIL_DIR)/uvd_error.cpp \
			$(UTIL_DIR)/uvd_log.cpp \
			$(UTIL_DIR)/uvd_priority_list.cpp \
			$(UTIL_DIR)/uvd_string_writer.cpp \
			$(UTIL_DIR)/uvd_types.cpp \
			$(UTIL_DIR)/uvd_util.cpp \
			$(UTIL_DIR)/uvd_util_string.cpp \
			$(UTIL_DIR)/uvd_util_file.cpp \
			$(UTIL_DIR)/uvd_version.cpp \

ROOT_DIR=..
# Suppose to be able to find makefile in dir above...but doesn't seem to
include $(ROOT_DIR)/Makefile.mk

