# UVD assembly engine plugin
# UVNet Universal Decompiler (uvudec)
# Copyright 2010 John McMaster <JohnDMcMaster@gmail.com>
# Licensed under the terms of the LGPL V3 or later, see COPYING for details

ROOT_DIR=../..

CC_SRCS =   \

CXX_SRCS = 	\
			data.cpp \
			header.cpp \
			init.cpp \
			object.cpp \
			plugin.cpp \
			relocation.cpp \
			string_table.cpp \
			symbol.cpp \
			writer.cpp \


include ../Makefile.mk

