# UVD assembly engine plugin
# UVNet Universal Decompiler (uvudec)
# Copyright 2010 John McMaster <JohnDMcMaster@gmail.com>
# Licensed under the terms of the LGPL V3 or later, see COPYING for details

ROOT_DIR=../..

CC_SRCS =   \

CXX_SRCS = 	\
			plugin.cpp \
			config.cpp \
			lib/bfd.cpp \
			lib/elf.cpp \
			lib/lib.cpp \
			args.cpp \
			flirt.cpp \
			function.cpp \
			pat/factory.cpp \
			pat/pat.cpp \
			pat/reader.cpp \
			sig/tree/basic_node.cpp \
			sig/tree/hash_node.cpp \
			sig/tree/leading_node.cpp \
			sig/format.cpp \
			sig/reader.cpp \
			sig/sig.cpp \
			sig/writer.cpp \

include ../Makefile.mk

